### ISSUE TITLE
Forked is a great name

### ISSUE THREAD

**Issue by catb0t** [aaronryank/Forked#2]
Given the whole point of the language, and its main unique feature compared with other 2 dimensional IP+stack based esoteric languages, Forked is an excellent name. IMNSHO.

**Comment by aaronryank** [comment]
Thanks, I agree :D I'm also going to make a multi-threaded version called Fred (Fork Thread).

**Comment by catb0t** [comment]
Now that you mention it, when I first saw the name, I kind of thought the `:` would cause the program to actually `fork()` for each possible branch direction, and each fork would run one  branch...

...which sounds like a very interesting and impractical esoteric execution model, and I'm going to have fun implementing that sometime in the future.

**Comment by aaronryank** [comment]
Yep, that's exactly what I plan to have Fred do.
