### ISSUE TITLE
Fork semantics could be more general

### ISSUE THREAD

**Issue by tsani** [aaronryank/Forked#3]
The semantics of the fork command are:

> if entered from right, the fork will direct the IP up if truthy and down if falsy. if entered from left, the fork will direct the IP down if truthy and up if falsy. if entered from top, the fork will direct the IP right if truthy and left if falsy. if entered from bottom, the fork will direct the IP left if truthy and right if falsy.

This behaviour seems internally inconsistent to me: the IP _turns right_ on truthy top of stack when entering the fork from the left or right, but the IP _turns left_ on truthy top of stack when entering from the top or bottom.

Instead, what do you think about the following semantics:

> The fork command may be entered from any direction, and changes the direction of the instruction pointer according to the value on top of the stack. If the value on top of the stack represents truth, then the instruction pointer _turns right_; else, it _turns left_.

This gives rise to the fun mnemonic: telling the truth is the _right_ thing to do.

**Comment by aaronryank** [comment]
Yes, that sounds a bit better, but what if it enters from the left and the top of stack is falsy? I don't want it to just reverse...

**Comment by Destructible-Watermelon** [comment]
does he mean turn right in general, rather than going right? as in entering from the left would cause the ip to go upwards?

**Comment by tsani** [comment]
@Destructible-Watermelon exactly. I mean that the IP *turns* right, so if it enters from the left, then it will go up; if it enters from the top, then it will go left; and so on.

**Comment by aaronryank** [comment]
Oh, okay. Yeah, that does make sense. I'll update that when I'm not on my phone.

**Comment by cairdcoinheringaahing** [comment]
Also, please don't change the name, I like it!

**Comment by catb0t** [comment]
@SatansSon see #2 :D

**Comment by aaronryank** [comment]
Fixed with commit 8.
